site_name: 我的技术文档
theme:
  name: material
  language: zh  # 设置中文
  features:
    - navigation.tabs # 顶部横向导航
    - navigation.sections # 侧边栏分组
    - search.suggest # 搜索建议
    - content.code.copy # 代码块复制按钮
  palette: 
    primary: indigo # 主题颜色
    accent: indigo

# 目录结构配置
nav:
  - overview: index.md
  - data:
    - data1: content.md
    - data2: content2.md
  - application:
    - application1: application1.md
  - technical guides:
    - technical-guide1: technical-guide1.md