site_name: 我的技术文档
theme:
  name: material
  language: zh  # 设置中文
  features:
    - navigation.tabs # 顶部横向导航
    - navigation.sections # 侧边栏分组
    - search.suggest # 搜索建议
    - content.code.copy # 代码块复制按钮
  palette: 
    primary: indigo # 主题颜色
    accent: indigo

# 目录结构配置
nav:
  - overview: index.md
  - data:
    - 二级目录: content.md
    - 二级目录2: content2.md
  - application:
  - technical guides: